### ISSUE TITLE
Base de donnée

### ISSUE THREAD

**Issue by Araylos** [Araylos/rp-manager#1]
- [x] Dictionnaire de données
- [x] MCD
- [x] MLD 
- [x] MPD

**Comment by peticle** [comment]
Redis-moi si il faut que je change des trucs au MCD, c'est une première version

**Comment by peticle** [comment]
Regarde plutôt le MLD du coup

**Comment by Araylos** [comment]
Faudrait qu'on ajoute tb_buff avec une valeur et un champs tour (Si il est remplie cela indique le nombre de tour ou le bonus / malusse est actif). Avec un lien sur la table la table object et un lien sur la table tb_stat. Comme ça on peut faire des potions de vie, armure etc... Après on peut aussi mettre un lien sur la tb_capac pour faire des sort de guérison, les attaques etc...

**Comment by peticle** [comment]
J'ai géré le tout dans la table associative ça me semblait plus logique.
altnumrnd = Le nombre de tour de l'altération, si c'est à NULL c'est infini
